### ISSUE TITLE
Not dropping with {drop: true} due to relationships of tables

### ISSUE THREAD

**Issue by saydus** [eveningkid/denodb#168]
It's failing to drop the tables on rerun of the server due to dependencies within table relations (I assume). Thus, I am manually dropping the schema.  
 
```
error: Uncaught (in promise) PostgresError: cannot drop table applications because other objects depend on it
  return new PostgresError(errorFields);
         ^
    at parseError (error.ts:106:10)
    at Connection._processError (connection.ts:434:19)
    at Connection._simpleQuery (connection.ts:298:20)
    at async Connection.query (connection.ts:546:16)
    at async Client.query (client.ts:25:12)
    at async PostgresConnector.query (postgres-connector.ts:60:22)
    at async Database.query (database.ts:164:21)
    at async Function.drop (model.ts:137:5)
    at async Database.sync (database.ts:129:9)
    at async app.ts:15:1
```

**Comment by rluvaton** [comment]
@saydus Thank you for your issue, can you please describe your DB structure so we can have better context when addressing this issue

**Comment by saydus** [comment]
Thanks for helping out, @rluvaton. [Here](https://gist.github.com/saydus/8fcfa7b56779a6b8002027a3370db468) are the models that I am linking in the database. 

One other thing I wanted to note is that there is a pivot table that I cannot link before the tables it is connecting - the documentation says to do that, but the error I am getting when the pivot table (`QuestionNote`) is listed before the tables (`Question`, `Note`) is:
```
error: Uncaught (in promise) PostgresError: relation "notes" does not exist
  return new PostgresError(errorFields);
         ^
    at parseError (error.ts:106:10)
    at Connection._processError (connection.ts:434:19)
    at Connection._simpleQuery (connection.ts:340:22)
    at async Connection.query (connection.ts:546:16)
    at async Client.query (client.ts:25:12)
    at async PostgresConnector.query (postgres-connector.ts:60:22)
    at async Database.query (database.ts:164:21)
    at async Function.createTable (model.ts:161:5)
    at async Database.sync (da
```

So for context, I changed the line `db.link([Application, CommitteeChoice, Question, Note, QuestionNote]);` in the linked gist to `db.link([Application, CommitteeChoice, QuestionNote, Question, Note]);`.

**Comment by rluvaton** [comment]
@saydus Please check if your error been solved in this https://github.com/eveningkid/denodb/pull/174 (change in your import to use this URL `https://raw.githubusercontent.com/rluvaton/denodb/fix/cant-drop-linked-tables-138/mod.ts`)

**Comment by saydus** [comment]
Hey @rluvaton! Thanks for working on the issue - unfortunately, the import is failing here: 
```
error: Uncaught TypeError: topologicalSort is not a function
  return (topologicalSort as unknown as (edges: [string, string][]) => string[])(
          ^
    at topologicalSortModelSchema (sort-model-schema.ts:40:11)
    at Database.link (database.ts:210:20)
    at database.ts:12:4
    at <anonymous> (<anonymous>)
```

**Comment by rluvaton** [comment]
I'll try to fix it later today

**Comment by rluvaton** [comment]
@saydus I fixed the import issue, although the tests still failing and I will discuss with @eveningkid about it I'll be happy if you could test it with the current update

**Comment by saydus** [comment]
Hey @rluvaton! Thanks for working on this! 

I am still getting this issue:
```
error: Uncaught TypeError: topologicalSort is not a function
  return (topologicalSort as unknown as (edges: [string, string][]) => string[])(
          ^
    at topologicalSortModelSchema (sort-model-schema.ts:40:11)
    at Database.link (database.ts:210:20)
    at database.ts:12:4
    at <anonymous> (<anonymous>)
```

Did I have to use a new link for the dependency?

**Comment by rluvaton** [comment]
> Hey @rluvaton! Thanks for working on this!
> 
> I am still getting this issue:
> 
> ```
> error: Uncaught TypeError: topologicalSort is not a function
>   return (topologicalSort as unknown as (edges: [string, string][]) => string[])(
>           ^
>     at topologicalSortModelSchema (sort-model-schema.ts:40:11)
>     at Database.link (database.ts:210:20)
>     at database.ts:12:4
>     at <anonymous> (<anonymous>)
> ```
> 
> Did I have to use a new link for the dependency?

Make sure you have upgraded to the latest version adding `--reload` to your `deno run` command:
> 
> ```shell
> deno run --reload script.ts
> ```

**Comment by saydus** [comment]
Hey @rluvaton!

```
error: Uncaught (in promise) PostgresError: cannot drop table applications because other objects depend on it
  return new PostgresError(errorFields);
         ^
    at parseError (error.ts:106:10)
    at Connection._processError (connection.ts:434:19)
    at Connection._simpleQuery (connection.ts:298:20)
    at async Connection.query (connection.ts:546:16)
    at async Client.query (client.ts:25:12)
    at async PostgresConnector.query (postgres-connector.ts:63:22)
    at async Database.query (database.ts:236:21)
    at async Function.drop (model.ts:137:5)
    at async Database.sync (database.ts:195:9)
    at async app.ts:19:1
```

Same error as before. Do you think it has to do with the order of table initialization? (pivot table last). I think documentation talks about adding pivot tables first, but that produces an error (I added another issue for that). 

Thanks for all the work!

**Comment by rluvaton** [comment]
> One other thing I wanted to note is that there is a pivot table that I cannot link before the tables it is connecting - the documentation says to do that, but the error I am getting when the pivot table (`QuestionNote`) is listed before the tables (`Question`, `Note`) is:
> 
> ```
> 
> error: Uncaught (in promise) PostgresError: relation "notes" does not exist
> 
>   return new PostgresError(errorFields);
> 
>          ^
> 
>     at parseError (error.ts:106:10)
> 
>     at Connection._processError (connection.ts:434:19)
> 
>     at Connection._simpleQuery (connection.ts:340:22)
> 
>     at async Connection.query (connection.ts:546:16)
> 
>     at async Client.query (client.ts:25:12)
> 
>     at async PostgresConnector.query (postgres-connector.ts:60:22)
> 
>     at async Database.query (database.ts:164:21)
> 
>     at async Function.createTable (model.ts:161:5)
> 
>     at async Database.sync (da
> 
> ```
> 

Is this issue solved?

**Comment by saydus** [comment]
Yes! @rluvaton, I just tested it and it seems to work now. The drop table issue still persists though:

```
error: Uncaught (in promise) PostgresError: cannot drop table applications because other objects depend on it
  return new PostgresError(errorFields);
         ^
    at parseError (error.ts:106:10)
    at Connection._processError (connection.ts:434:19)
    at Connection._simpleQuery (connection.ts:298:20)
    at async Connection.query (connection.ts:546:16)
    at async Client.query (client.ts:25:12)
    at async PostgresConnector.query (postgres-connector.ts:63:22)
    at async Database.query (database.ts:236:21)
    at async Function.drop (model.ts:137:5)
    at async Database.sync (
```

**Comment by rluvaton** [comment]
@saydus it _should_ be fixed now, please try again (don't forget the `--reload` flag)

**Comment by saydus** [comment]
It's fixed @rluvaton!

Thank you for your help! Do you know if database migrations are in the plans for the project?

**Comment by rluvaton** [comment]
> It's fixed @rluvaton!
> 
> 
> 
> Thank you for your help! Do you know if database migrations are in the plans for the project? 

I don't know but you should open an issue about this feature request.

As this project keep growing we need more maintainers to help, we would love if you could add a PR for your requested feature

**Comment by saydus** [comment]
Sounds good! I will try work on it as I finish things I am working on right now. Do you guys have Discord for communicating about the project?

**Comment by rluvaton** [comment]
> Sounds good! I will try work on it as I finish things I am working on right now. Do you guys have Discord for communicating about the project? 

@eveningkid

**Comment by rluvaton** [comment]
> Sounds good! I will try work on it as I finish things I am working on right now. Do you guys have Discord for communicating about the project? 

@saydus We don't have a Discord channel, we use GitHub to communicate.
